version: 2
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "daily"
    target_branch: "main"
    default_assignees:
      - "0xflotus"
    commit_message:
      prefix: "chore"
