name: test-ip2d
run-name: Testing ip2d
on: 
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'Cargo.toml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'Cargo.toml'
jobs:
  test:
    strategy:
      matrix:
        version: 
          - stable
          - '1.82'
          - '1.75'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g bats
      - run: bats -v
      - run: rustup default ${{ matrix.version }}
      - run: cargo -V
      - run: rustc -V
      - run: cargo test
      - run: cargo build --release
      - run: bats test/test.bats
